### ISSUE TITLE
Errors in Mac Installation

### ISSUE THREAD

**Issue by asulit08** [Russel88/DAtest#11]
Hi, I am having trouble installing this on a Mac (Mojave) using Rstudio 1.2.1335 and R v 3.6. I think it has something to do with compilation errors. 

I either run into "library not found for -lgfortran" for either minqa or RcppEigen:
    I am able to solve this by adding a makevars file that points to a homebrew installation of gcc

However when I do the makevars workaround, I encounter a cross-compilation error for nloptr

I hope you can advise me on this

**Comment by Russel88** [comment]
Hi. Have you tried only setting the makevars for gfortran? See more here: https://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks--lgfortran-and--lquadmath-error/

Hope it helps

**Comment by asulit08** [comment]
Hi! That worked! Thanks!
