### ISSUE TITLE
Adding interaction terms in DA.neb()

### ISSUE THREAD

**Issue by fconstancias** [Russel88/DAtest#12]
Dear all,

I am analyzing a mice experiment where we followed gut microbiota over time. Mice (expet a control) recieved a DSS stress to induce severe colitis and mices recived 4 different treatments (Fecal Microbial Transplants) (+ some controls) in order to test if it helped to recover.

I would like to test OTU which are influenced by treatment at all the time points. Hence,starting from a phyloseq object, I have started to use the following DAtest workflow:
```

physeq %>%
        preDA(min.samples = 200,
                  min.reads = 10, 
                  min.abundance = 0) %>%
        DA.neb(predictor = "treatment", 
                  paired = "mouse_label",  
                  covars = c("day"),
                  allResults = TRUE,
                  relative = FALSE) -> results
```

Then I am exploring the results using, in order to have the comparaisons for all the different contrasts treatment and time:

```
results %>%
  DA.lsmeans(variable = c("day", "predictor"))

```
or 

```
emmeans(results[[i]], 
        pairwise ~ predictor | day,
          adjust = "FDR", type = "response")$contrasts %>% 
  as.data.frame()
```

However, I am not sure this is correct since according to the formula in DA.neb() the interaction is not taken into account i.e., + instead of *
```

tryCatch(fit <- lme4::glmer.nb(as.formula(paste("x ~ predictor+offset(log(libSize)) + (1|paired)+", 
                                                        paste(names(covars), collapse = "+"), sep = "")), 
                                       ...), error = function(x) fit <- NULL)
```

Do you know if this is correct? Would it be possible to add * in the formula ? 
If you have any suggestion to help solving my question, feel free !

Thanks a ton.

**Comment by Russel88** [comment]
Hi fconstancias,

DAtest does not support interaction terms, unfortunately. 

You could however make a new variable which represents the interaction and include that in the model: 
`sample_data(physeq)$treatment_day <- interaction(sample_data(physeq)[, "treatment"]), sample_data(physeq)[, "day"]))`

And then run the model:
`results <-  DA.neb(predictor = "treatment", 
                  paired = "mouse_label",  
                  covars = c("day", "treatment_day"),
                  allResults = TRUE,
                  relative = FALSE)`

The A*B in a formula simply expands to A + B + A:B and the result would thus be the same. The `testDA` results would not be valid with this trick, however.

Be aware that the `neb` model has a tendency of too many false positives, but since you have added `relative = FALSE` you might have absolute abundances?

Hope it helps.

Cheers,
Jakob

**Comment by fconstancias** [comment]
Hi Jakob,

Thanks a lot for the suggestion and noticing the `relative = FALSE` mistake, I do not have absolute counts.

I have tried the approach on a reduced dataset and this is the glm for one ASV : ASV0840.

```
$ASV0840
Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) ['glmerMod']
 Family: Negative Binomial(3.4077)  ( log )
Formula: x ~ predictor + offset(log(libSize)) + (1 | paired) + day + treatment_day
      AIC       BIC    logLik  deviance  df.resid 
 4282.234  4371.052 -2115.117  4230.234       199 
Random effects:
 Groups Name        Std.Dev. 
 paired (Intercept) 3.183e-05
Number of obs: 225, groups:  paired, 48
Fixed Effects:
                    (Intercept)               predictorDysbiotic                predictorEubiotic  
                       -1.31888                          0.51465                          0.22462  
                   predictorH2O             predictorNormobiotic                  predictorPredni  
                        1.23291                          0.27400                          0.48492  
                      dayDay_12                        dayDay_14                         dayDay_6  
                       -0.35850                         -1.05401                         -1.50595  
  treatment_dayDysbiotic_Day_-1     treatment_dayEubiotic_Day_-1          treatment_dayH2O_Day_-1  
                       -0.48006                         -0.31572                         -1.30643  
treatment_dayNormobiotic_Day_-1       treatment_dayPredni_Day_-1          treatment_dayDSS_Day_12  
                       -0.14422                         -0.33205                         -0.06111  
  treatment_dayDysbiotic_Day_12     treatment_dayEubiotic_Day_12          treatment_dayH2O_Day_12  
                       -0.72262                         -0.23655                         -0.81040  
treatment_dayNormobiotic_Day_12          treatment_dayDSS_Day_14    treatment_dayDysbiotic_Day_14  
                       -0.73824                          0.19146                          0.28458  
   treatment_dayEubiotic_Day_14          treatment_dayH2O_Day_14  treatment_dayNormobiotic_Day_14  
                        0.60078                         -0.67101                          0.30148  
fit warnings:
fixed-effect model matrix is rank deficient so dropping 8 columns / coefficients
convergence code 0; 0 optimizer warnings; 1 lme4 warnings 
```

Then the output of :
```
results$ASV0840 %>%
  summary()
```

```
Fixed effects:
                                Estimate Std. Error z value Pr(>|z|)    
(Intercept)                     -1.31888    0.19184  -6.875 6.20e-12 ***
predictorDysbiotic               0.51465    0.29262   1.759  0.07861 .  
predictorEubiotic                0.22462    0.32777   0.685  0.49316    
predictorH2O                     1.23291    0.29251   4.215 2.50e-05 ***
predictorNormobiotic             0.27400    0.29273   0.936  0.34926    
predictorPredni                  0.48492    0.31290   1.550  0.12119    
dayDay_12                       -0.35850    0.41369  -0.867  0.38616    
dayDay_14                       -1.05401    0.39253  -2.685  0.00725 ** 
dayDay_6                        -1.50595    0.29267  -5.145 2.67e-07 ***
treatment_dayDysbiotic_Day_-1   -0.48006    0.39887  -1.204  0.22876    
treatment_dayEubiotic_Day_-1    -0.31572    0.42504  -0.743  0.45760    
treatment_dayH2O_Day_-1         -1.30643    0.39926  -3.272  0.00107 ** 
...

```
suggests that day (covars) and treatment (predictor) are singnificant, same for treatment_day covars.


Since I have specified the interaction term, are those approaches correct to extract : 

- how time (day) and predictor (treatment) do influence its proportion:
  
 ```
 emmeans::emmeans(results[["ASV0840"]], 
            pairwise ~ predictor | day,
            adjust = "FDR", type = "response")$contrasts %>% 
      as.data.frame()

NOTE: A nesting structure was detected in the fitted model:
    treatment_day %in% (predictor*day)
                  contrast    day     ratio         SE  df     z.ratio      p.value
1          DSS / Dysbiotic Day_-1 0.9660077 0.26187720 Inf -0.12757088 0.9483390146
2           DSS / Eubiotic Day_-1 1.0953827 0.29685751 Inf  0.33616643 0.9483390146
3                DSS / H2O Day_-1 1.0762865 0.29242479 Inf  0.27058239 0.9483390146
...
27       Eubiotic / Predni Day_12 0.6084407 0.17053173 Inf -1.77273338 0.1812601018
28       **H2O / Normobiotic Day_12 2.4272207 0.65755557 Inf  3.27322951 0.007974457**7
..

```
and here for instance this ASV is significantly differentially abundant at Day_12 between H2O and Normobiotic group.

- if the proportion of this particular taxa  (ASV0840) is changing over time no matter the treatment's group:
```
    emmeans::emmeans(results[["ASV0840"]], 
                     pairwise ~ day,
                     adjust = "FDR", type = "response")$contrasts %>% 
      as.data.frame() %>%
      rename('p.adj' = p.value)

NOTE: A nesting structure was detected in the fitted model:
    treatment_day %in% (predictor*day)
         contrast    ratio        SE  df  z.ratio        p.adj
1 Day_-1 / Day_12 1.428904 0.1599700 Inf 3.188015 1.719039e-03
2 Day_-1 / Day_14 1.659283 0.1609506 Inf 5.220461 2.677181e-07
3  Day_-1 / Day_6 2.933521 0.3413265 Inf 9.249402 1.354514e-19
4 Day_12 / Day_14 1.161228 0.1143090 Inf 1.518495 1.288896e-01
5  Day_12 / Day_6 2.052987 0.2413448 Inf 6.118652 2.831099e-09
6  Day_14 / Day_6 1.767945 0.1828415 Inf 5.509730 7.187687e-08
```

- if its proportion changing over treatment not taking into account day:

```
    emmeans::emmeans(results[["ASV0840"]], 
                     pairwise ~ predictor,
                     adjust = "FDR", type = "response")$contrasts %>% 
      as.data.frame() %>%
      rename('p.adj' = p.value) 

NOTE: A nesting structure was detected in the fitted model:
    treatment_day %in% (predictor*day)
                  contrast     ratio         SE  df    z.ratio      p.adj
1          DSS / Dysbiotic 0.7768295 0.10175117 Inf -1.9279991 0.11540408
2           DSS / Eubiotic 0.8153346 0.11274839 Inf -1.4763496 0.26221887
3                DSS / H2O 0.6044954 0.07921204 Inf -3.8413290 0.00183555
...

```

Are those approaches and syntax correct to get those information or should I also include the interaction term `treatment_day` somehow ?

**Comment by Russel88** [comment]
It seems that maybe your model is too complex for your data. You have 225 samples from 48 mice, and you're trying to fit 25 parameters. glmer is also telling you that your model matrix is rank deficient, so it seems that you do not have measurements for all treatments on all days? I suggest simplifying your model, either by dropping the interaction, treating time as continuous, grouping time points in before/after or early/late, or some other way.

 If you want the model as it is now, I think you need to define manual contrasts for getting pairwise comparisons, which includes the interaction effect. Maybe emmeans can do this automatically if we hadn't used the interaction trick. You could copy the code from DAtest, and change this yourself to make it fit your purpose

**Comment by fconstancias** [comment]
thanks @Russel88
