### ISSUE TITLE
Preform comparisons on rank (i.e. family) level instead of OTU

### ISSUE THREAD

**Issue by DitteOL** [Russel88/DAtest#15]
Hi

Is it possible to do abundance comparisons between groups on rank (i.e. family) level instead of specific OTU. 

Thanks, Ditte

**Comment by Russel88** [comment]
Hi Ditte

Yes, that is possible. If you have a phyloseq object you just run tax_glom() prior to any DAtest analysis, like so:
`phy_family <- tax_glom(phy, "Family")`
`res <- testDA(phy_family, ...)`

**Comment by DitteOL** [comment]
Hej Jakob

This of course worked perfectly. Thanks you so much and for your fast reply!

/Ditte
