### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by tumu0901** [Russel88/DAtest#17]
Hi，
I tried to install the package for different methods. But I got errors showing below.
`package ‘testthat’ successfully unpacked and MD5 sums checked
Error: Failed to install 'DAtest' from GitHub:
  (converted from warning) cannot remove the prior installation of package ‘testthat’`
I also tried to remove the package 'testthat', but I don't have it.
` remove.packages("testthat")
Removing package from ‘C:/Users/lqwnc/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)`

Wondering do you have other suggestions? Thank you very much!

**Comment by Russel88** [comment]
This is a common installation error, not specifically associated with DAtest. Often just restarting R will help (if you open R with command line, use --vanilla), and then install DAtest again (don't load any packages prior to installing). If this doesn't work, then look in your library folder, and if there is a folder named testthat, then delete it, and try to install DAtest again.

**Comment by tumu0901** [comment]
It works! Yeah, Thank you very much.
