### ISSUE TITLE
Error in rowSums

### ISSUE THREAD

**Issue by ofleitas** [Russel88/DAtest#20]
Hello 

I am trying to analyse RNA-seq data with testDA function but i get this return :

606 empty features removed
Running on 3 cores
predictor is assumed to be a categorical variable with 6 levels: ct1, ct2, ct3, rst1, rst2, rst3
Spikeing...
Error in rowSums(count_table[, predictor == 1]) : 
  'x' must be an array of at least two dimensions

**Comment by Russel88** [comment]
Hi ofleitas,

I need some more information to figure out what's going on.
How many samples and features are in your input? 
Are you using phyloseq as input or a data.frame?

**Comment by ofleitas** [comment]
Hello
My input contains 6 samples, 3 from a control condition and 3 from a
treatment condition and the features are 5799. I am using a data frame as
input.

**Comment by Russel88** [comment]
I looks like your predictor variable is wrong. The output says ct1, ct2, ct3, rst1, rst2, rst3. Your predictor should have the same value for all controls and same value for all treatments. Else it looks like there are six conditions with only 1 sample in each

**Comment by ofleitas** [comment]
Thank you very much for the reply. Is there a predictor file available that
can be used as an example so that users can be guided in its preparation?

**Comment by Russel88** [comment]
I don't have an example, unfortunately. But in your case it could be predictor = c("ct", "ct", "ct", "rst", "rst", "rst"), if that matches the order of the columns in the input data.frame.

**Comment by ofleitas** [comment]
Hello

Thank you very much for the suggestion, the analysis worked well.
