### ISSUE TITLE
allDA(): Undeclared reference to function

### ISSUE THREAD

**Issue by jberry47** [Russel88/DAtest#3]
Trying to run `t <- allDA(sub,predictor=conds)` and it seems to get to 100% completed but I get an error at the last moment of `Error in tax_table(data, errorIfNULL = FALSE) : could not find function "tax_table"`

By the way this is fantastic work thanks so much for this

**Comment by Russel88** [comment]
Thanks for reporting the bug, it should work now.

I'm glad you like it
