### ISSUE TITLE
Fail to install the DAtest

### ISSUE THREAD

**Issue by pwang16** [Russel88/DAtest#4]
Hi Russel,
Please have a look at the error information I pasted in the below, I can not install the DAtest using the command "install_github("Russel88/DAtest")". Could you please let me know how to fix it? Thanks.
Best regards,
Peng

> install_github("Russel88/DAtest")
Downloading GitHub repo Russel88/DAtest@master
from URL https://api.github.com/repos/Russel88/DAtest/zipball/master
Installing DAtest
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/rg/2w1f9r6s6gv6fg1m3zj5xrl00000gn/T/Rtmp1Gw7Ah/devtools91d67aa0169/Russel88-DAtest-fb3a1af'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘DAtest’ ...
** R
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘pscl’
ERROR: lazy loading failed for package ‘DAtest’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/DAtest’
Installation failed: Command failed (1)

**Comment by Russel88** [comment]
Hi Peng,
It was a bug, it should be fixed now if you try again. Let me know if you are still encountering problems. Thank you for reporting the bug.
Cheers,
Jakob

**Comment by pwang16** [comment]
Hi Jakob,

It works now. Thanks a lot. Have a nice day.

Best regards,
Peng
