### ISSUE TITLE
showing p-value on the graphs

### ISSUE THREAD

**Issue by saifsikdar** [Russel88/DAtest#8]
Hi  @Russel88 
I am a new R user.  After performing a statistical significance test, I would like to show the p-value of the microbiota abundant graphs on top of the compared groups or near to the figure legends.  Could you please let me know how can I do this?
Thanks,
Saif

**Comment by Russel88** [comment]
Hi Saif
If you're using the `featurePlot` function, you can use `annotate`, for example:
`featurePlot(data, predictor) + annotate("text", label = "p = 0.002", x = 0.5, y = 1)`
But you would have to adjust p-value, x, and y values manually.

`featurePlot` makes a ggplot2 object, so you can modify it with all the usual ggplot2 functions.
For more on how to use ggplot2 for plotting see here: http://r4ds.had.co.nz/data-visualisation.html
