### ISSUE TITLE
Score = 0 for all tests and elaboration on running PCoA prior to DAtest

### ISSUE THREAD

**Issue by CarlyMuletzWolz** [Russel88/DAtest#9]
Hi,

Thank you for the great package. 

What does it mean when all of the tests have a score = 0. That there are essentially no features that differ in abundance, so the function cannot calculate a score? 

This has happened to me with two different datasets, and particularly since I started using dada2 and ASV methods, where far fewer features are shared among samples. 

In one of those instances there was a clear difference in the PCoA plot and accompanying statistics between the two treatments I was looking at. My question here is why does that matter? Wouldn't you be interested in what features are differing between treatments because you see differences in beta diversity? I'm missing why you shouldn't move forward with analyses in that case. You have this listed as your assumptions in the introduction section of the github. It reads:

'Assumptions
The method assumes that most features are NOT associated with the predictor. It is therefore advised to first run an ordination (PCA/PCoA) or similar and if there is clear separation associated with the predictor, DAtest should not be used. In this case, only the False Positive Rate (FPR) can be used.'

What would you do with the FPR in that case? Would you use that to rank which test to use instead of the score?

In this last time I used DAtest, there was no clear separation in treatments in PCoA, but I still received a score of all 0s for the tests. 

Thank you for any guidance. 
-Carly

**Comment by Russel88** [comment]
Hi Carly,

That all methods have a Score <= 0 does not mean that no features differ. It means that all methods have a false discovery rate as least as high the emperical power (adjusted by the AUC, see wiki for details).

DAtest uses the variation in your dataset to estimate how well different methods perform. But if much of this variation comes from the predictor of interest the methods will appear worse than they actually are. 

This does not mean that you cannot use tests of differential abundance, you just cannot rely on the ranking of methods that DAtest gives you. You can however use the False Positive Rate to filter out methods that give too many false positives (this does not rely on spike-ins, and is therefore not affected by this issue).

Hope this makes sense,

Cheers,
